"""add shop_follows

Revision ID: 2d9d01a15fef
Revises: d09a0a8ea5bc
Create Date: 2026-08-05 05:43:35.876125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9d01a15fef'
down_revision: Union[str, None] = 'd09a0a8ea5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_follows',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_follows_shop_id_shops'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shop_follows_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_follows')),
    sa.UniqueConstraint('user_id', 'shop_id', name='uq_shop_follows_user_shop')
    )
    op.create_index(op.f('ix_shop_follows_shop_id'), 'shop_follows', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shop_follows_user_id'), 'shop_follows', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_follows_user_id'), table_name='shop_follows')
    op.drop_index(op.f('ix_shop_follows_shop_id'), table_name='shop_follows')
    op.drop_table('shop_follows')
    # ### end Alembic commands ###
