"""add page sections

Revision ID: 3f18e879d84e
Revises: 46c7b654c1b7
Create Date: 2026-08-06 16:54:36.609891

"""
from typing import Sequence, Union

import uuid
from datetime import UTC, datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f18e879d84e'
down_revision: Union[str, None] = '46c7b654c1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_sections',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('section_type', sa.Enum('hero', 'stats', 'top_products', 'latest_listings', 'featured_shops', 'categories', 'how_it_works', 'reviews', 'cta', 'newsletter', name='section_type'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_sections')),
    sa.UniqueConstraint('key', name=op.f('uq_page_sections_key'))
    )
    op.create_index('ix_page_sections_sort_order', 'page_sections', ['sort_order'], unique=False)
    # ### end Alembic commands ###

    # Seed the page exactly as it is rendered today, in the same order, so this
    # migration changes nothing visible. The landing page becomes data-driven
    # without becoming different — an empty table would blank the homepage.
    sections = sa.table(
        "page_sections",
        sa.column("id", sa.Uuid()),
        sa.column("key", sa.String()),
        # The real column is the section_type enum, not text; declaring it as
        # String here made the insert fail with DatatypeMismatchError.
        # create_type=False because create_table above already made the type.
        sa.column("section_type", postgresql.ENUM(name="section_type", create_type=False)),
        sa.column("sort_order", sa.Integer()),
        sa.column("is_active", sa.Boolean()),
        sa.column("settings", postgresql.JSONB()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(UTC)
    order = [
        ("hero", "hero"),
        ("stats", "stats"),
        ("top-products", "top_products"),
        ("latest-listings", "latest_listings"),
        ("featured-shops", "featured_shops"),
        ("categories", "categories"),
        ("how-it-works", "how_it_works"),
        ("reviews", "reviews"),
        ("cta", "cta"),
        ("newsletter", "newsletter"),
    ]
    op.bulk_insert(
        sections,
        [
            {
                "id": uuid.uuid4(),
                "key": key,
                "section_type": section_type,
                "sort_order": index,
                "is_active": True,
                # Empty: every string falls back to the bundled translations,
                # so the seeded page is byte-for-byte what shipped.
                "settings": {},
                "created_at": now,
                "updated_at": now,
            }
            for index, (key, section_type) in enumerate(order)
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_sections_sort_order', table_name='page_sections')
    op.drop_table('page_sections')
    # ### end Alembic commands ###
