"""add otp attempts counter

Revision ID: 445c2da8c2d7
Revises: 7ae776286dae
Create Date: 2026-08-01 09:41:24.918559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445c2da8c2d7'
down_revision: Union[str, None] = '7ae776286dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('attempts', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_tokens', 'attempts')
    # ### end Alembic commands ###
