"""add categories and listing category

Revision ID: 6605a57ca25d
Revises: bc75b0879d9c
Create Date: 2026-08-05 16:33:18.864510

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6605a57ca25d'
down_revision: Union[str, None] = 'bc75b0879d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Seeded here rather than in a separate script so a fresh database comes up
# usable — a category system with no categories is worse than none, since
# the listing form would offer an empty required dropdown.
#
# Scoped to what JU students actually trade. Two levels only; see the model
# docstring for why.
TAXONOMY: list[tuple[str, str, str, list[tuple[str, str]]]] = [
    ("Books & Study", "books-study", "📚", [
        ("Textbooks", "textbooks"),
        ("Notes & Guides", "notes-guides"),
        ("Stationery", "stationery"),
    ]),
    ("Electronics", "electronics", "💻", [
        ("Laptops & Computers", "laptops-computers"),
        ("Mobiles & Tablets", "mobiles-tablets"),
        ("Audio & Headphones", "audio-headphones"),
        ("Accessories & Chargers", "accessories-chargers"),
    ]),
    ("Hostel & Living", "hostel-living", "🛏️", [
        ("Furniture", "furniture"),
        ("Bedding", "bedding"),
        ("Kitchen & Appliances", "kitchen-appliances"),
        ("Storage & Organisers", "storage-organisers"),
    ]),
    ("Fashion", "fashion", "👕", [
        ("Clothing", "clothing"),
        ("Shoes", "shoes"),
        ("Bags & Backpacks", "bags-backpacks"),
        ("Watches & Accessories", "watches-accessories"),
    ]),
    ("Food & Homemade", "food-homemade", "🍱", [
        ("Homemade Meals", "homemade-meals"),
        ("Snacks & Drinks", "snacks-drinks"),
        ("Baked Goods", "baked-goods"),
    ]),
    ("Sports & Fitness", "sports-fitness", "🏏", [
        ("Sports Equipment", "sports-equipment"),
        ("Cycles", "cycles"),
        ("Gym & Fitness", "gym-fitness"),
    ]),
    ("Services", "services", "🛠️", [
        ("Tutoring", "tutoring"),
        ("Printing & Photocopy", "printing-photocopy"),
        ("Repairs", "repairs"),
        ("Photography & Events", "photography-events"),
    ]),
    ("Other", "other", "📦", [
        ("Miscellaneous", "miscellaneous"),
    ]),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index('ix_categories_parent_sort', 'categories', ['parent_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('listings', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_listings_category_id'), 'listings', ['category_id'], unique=False)
    op.create_foreign_key(op.f('fk_listings_category_id_categories'), 'listings', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    _seed_taxonomy()


def _seed_taxonomy() -> None:
    categories = sa.table(
        "categories",
        sa.column("id", sa.Uuid),
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
        sa.column("icon", sa.String),
        sa.column("parent_id", sa.Uuid),
        sa.column("sort_order", sa.Integer),
    )

    rows = []
    for parent_order, (name, slug, icon, children) in enumerate(TAXONOMY):
        parent_id = uuid.uuid4()
        rows.append({
            "id": parent_id,
            "name": name,
            "slug": slug,
            "icon": icon,
            "parent_id": None,
            "sort_order": parent_order,
        })
        for child_order, (child_name, child_slug) in enumerate(children):
            rows.append({
                "id": uuid.uuid4(),
                "name": child_name,
                "slug": child_slug,
                # Children inherit the parent's icon in the UI, so leaving
                # this null keeps the taxonomy easy to re-theme in one place.
                "icon": None,
                "parent_id": parent_id,
                "sort_order": child_order,
            })

    op.bulk_insert(categories, rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_listings_category_id_categories'), 'listings', type_='foreignkey')
    op.drop_index(op.f('ix_listings_category_id'), table_name='listings')
    op.drop_column('listings', 'category_id')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index('ix_categories_parent_sort', table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
