"""listing status controls and restock requests

Adds the pieces behind Phase 53: a seller-reversible `paused` status, manual
per-shop listing order, out-of-stock restock requests, and removes
`quantity` now that a manual out-of-stock toggle replaces it as the thing
that used to derive `out_of_stock` from `quantity` hitting zero.

Revision ID: 6905f440f5d9
Revises: b353331cb102
Create Date: 2026-08-07 07:02:18.652078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6905f440f5d9'
down_revision: Union[str, None] = 'b353331cb102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic does not diff enum values; hand-written, as for `expired`,
    # `both`, and `moderator` before them. Safe inside the transaction on
    # PG 12+ because neither new label is used by any statement in this
    # migration.
    op.execute("ALTER TYPE listing_status ADD VALUE IF NOT EXISTS 'paused'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'restock_available'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_restock_requests',
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_listing_restock_requests_buyer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_listing_restock_requests_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_restock_requests'))
    )
    op.create_index(op.f('ix_listing_restock_requests_buyer_id'), 'listing_restock_requests', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_listing_restock_requests_listing_id'), 'listing_restock_requests', ['listing_id'], unique=False)
    op.create_index('uq_restock_request_pending', 'listing_restock_requests', ['listing_id', 'buyer_id'], unique=True, postgresql_where='fulfilled_at IS NULL')
    op.add_column('listings', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_listings_shop_id_sort_order', 'listings', ['shop_id', 'sort_order'], unique=False)
    op.drop_constraint(op.f('ck_listings_quantity_non_negative'), 'listings', type_='check')
    op.drop_column('listings', 'quantity')
    # ### end Alembic commands ###

    # Backfill so the new manual order reproduces exactly what every shop's
    # storefront and "My listings" already show today (newest first) —
    # nothing visibly reshuffles the day this ships. sort_order 0 = shown
    # first, so it has to ascend in the *opposite* direction from
    # created_at for "ascending sort_order" to mean "newest first".
    op.execute(
        """
        UPDATE listings
        SET sort_order = ranked.rank - 1
        FROM (
            SELECT id, ROW_NUMBER() OVER (
                PARTITION BY shop_id ORDER BY created_at DESC
            ) AS rank
            FROM listings
            WHERE shop_id IS NOT NULL
        ) AS ranked
        WHERE listings.id = ranked.id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False, server_default='1'))
    op.create_check_constraint(op.f('ck_listings_quantity_non_negative'), 'listings', 'quantity >= 0')
    op.drop_index('ix_listings_shop_id_sort_order', table_name='listings')
    op.drop_column('listings', 'sort_order')
    op.drop_index('uq_restock_request_pending', table_name='listing_restock_requests', postgresql_where='fulfilled_at IS NULL')
    op.drop_index(op.f('ix_listing_restock_requests_listing_id'), table_name='listing_restock_requests')
    op.drop_index(op.f('ix_listing_restock_requests_buyer_id'), table_name='listing_restock_requests')
    op.drop_table('listing_restock_requests')
    # ### end Alembic commands ###
    # Postgres cannot drop an enum value or un-add one. Reversing `paused`
    # and `restock_available` means recreating listing_status and
    # notification_type and deciding what happens to any row currently using
    # them — a data question, not a schema one, left to whoever needs it.
