"""add ju student fields and reference tables

Revision ID: 7ae776286dae
Revises: d47568a4caea
Create Date: 2026-08-01 09:31:18.011511

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae776286dae'
down_revision: Union[str, None] = 'd47568a4caea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


HALLS = [
    "Al Beruni Hall",
    "A F M Kamaluddin Hall",
    "Jahanara Imam Hall",
    "Nawab Faizunnesa Hall",
    "Pritilata Hall",
    "Sher-e-Bangla A. K. Fazlul Haq Hall",
    "Begum Khaleda Zia Hall",
    "Maulana Bhashani Hall",
    "Mir Mosharraf Hossain Hall",
    "Shaheed Salam-Barkat Hall",
    "Shaheed Rafiq-Jabbar Hall",
    "July 24 Jagoroni Hall",
    "Shaheed Felani Khatun Hall",
    "Bishwakabi Rabindranath Tagore Hall",
    "Begum Sufia Kamal Hall",
    "Rokeya Hall",
    "Fazilatunnesa Hall",
    "Bir Protik Taramon Bibi Hall",
    "Shaheed Tajuddin Ahmad Hall",
    "Nawab Salimullah Hall",
    "Jatiya Kabi Kazi Nazrul Islam Hall",
]

DEPARTMENTS = [
    # (name, faculty)
    ("International Relations", "Faculty of Arts & Humanities"),
    ("English", "Faculty of Arts & Humanities"),
    ("History", "Faculty of Arts & Humanities"),
    ("Philosophy", "Faculty of Arts & Humanities"),
    ("Drama and Dramatics", "Faculty of Arts & Humanities"),
    ("Archaeology", "Faculty of Arts & Humanities"),
    ("Bangla", "Faculty of Arts & Humanities"),
    ("Journalism and Media Studies", "Faculty of Arts & Humanities"),
    ("Fine Art", "Faculty of Arts & Humanities"),
    ("Computer Science and Engineering", "Faculty of Mathematical & Physical Sciences"),
    ("Mathematics", "Faculty of Mathematical & Physical Sciences"),
    ("Physics", "Faculty of Mathematical & Physical Sciences"),
    ("Environmental Sciences", "Faculty of Mathematical & Physical Sciences"),
    ("Statistics and Data Science", "Faculty of Mathematical & Physical Sciences"),
    ("Geological Sciences", "Faculty of Mathematical & Physical Sciences"),
    ("Chemistry", "Faculty of Mathematical & Physical Sciences"),
    ("Economics", "Faculty of Social Sciences"),
    ("Urban & Regional Planning", "Faculty of Social Sciences"),
    ("Anthropology", "Faculty of Social Sciences"),
    ("Geography & Environment", "Faculty of Social Sciences"),
    ("Government & Politics", "Faculty of Social Sciences"),
    ("Public Administration", "Faculty of Social Sciences"),
    ("Botany", "Faculty of Biological Sciences"),
    ("Biochemistry & Molecular Biology", "Faculty of Biological Sciences"),
    ("Zoology", "Faculty of Biological Sciences"),
    ("Pharmacy", "Faculty of Biological Sciences"),
    ("Microbiology", "Faculty of Biological Sciences"),
    ("Biotechnology & Genetic Engineering", "Faculty of Biological Sciences"),
    ("Public Health and Informatics", "Faculty of Biological Sciences"),
    ("Finance & Banking", "Faculty of Business Studies"),
    ("Marketing", "Faculty of Business Studies"),
    ("Accounting and Information Systems", "Faculty of Business Studies"),
    ("Management Studies", "Faculty of Business Studies"),
    ("Law & Justice", "Faculty of Law"),
    ("Institute of Information Technology", "Institute"),
    ("Institute of Remote Sensing and GIS", "Institute"),
    ("Institute of Comparative Literature and Culture", "Institute"),
    ("Institute of Business Administration", "Institute"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('faculty', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('halls',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_halls')),
    sa.UniqueConstraint('name', name=op.f('uq_halls_name'))
    )

    halls_table = sa.table('halls', sa.column('id', sa.Uuid()), sa.column('name', sa.String))
    op.bulk_insert(halls_table, [{"id": uuid.uuid4(), "name": name} for name in HALLS])

    departments_table = sa.table(
        'departments',
        sa.column('id', sa.Uuid()),
        sa.column('name', sa.String),
        sa.column('faculty', sa.String),
    )
    op.bulk_insert(
        departments_table,
        [{"id": uuid.uuid4(), "name": name, "faculty": faculty} for name, faculty in DEPARTMENTS],
    )

    op.add_column('users', sa.Column('student_id', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('registration_no', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('hall_id', sa.Uuid(), nullable=False))
    op.add_column('users', sa.Column('department_id', sa.Uuid(), nullable=False))
    op.add_column('users', sa.Column('session', sa.String(length=7), nullable=False))
    op.add_column('users', sa.Column('batch', sa.SmallInteger(), nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_hall_id'), 'users', ['hall_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_registration_no'), 'users', ['registration_no'])
    op.create_unique_constraint(op.f('uq_users_student_id'), 'users', ['student_id'])
    op.create_foreign_key(op.f('fk_users_hall_id_halls'), 'users', 'halls', ['hall_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_users_department_id_departments'), 'users', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_department_id_departments'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_hall_id_halls'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('uq_users_student_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_registration_no'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_hall_id'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('users', 'batch')
    op.drop_column('users', 'session')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'hall_id')
    op.drop_column('users', 'registration_no')
    op.drop_column('users', 'student_id')
    op.drop_table('halls')
    op.drop_table('departments')
    # ### end Alembic commands ###
