"""listing views, expiry and promotion

Revision ID: 87818c74aa4c
Revises: 8bbd9579765f
Create Date: 2026-08-06 02:04:47.331393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87818c74aa4c'
down_revision: Union[str, None] = '8bbd9579765f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic's autogenerate does not diff enum values, so this is hand-written.
    # Safe inside the migration's transaction on PG 12+ as long as the new
    # label isn't *used* in the same transaction — the backfill below only
    # touches rows that are already 'active'.
    op.execute("ALTER TYPE listing_status ADD VALUE IF NOT EXISTS 'expired'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_views',
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('viewer_key', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_listing_views_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_views')),
    sa.UniqueConstraint('listing_id', 'viewer_key', 'window_start', name='uq_listing_view_window')
    )
    op.create_index('ix_listing_views_listing_id_created_at', 'listing_views', ['listing_id', 'created_at'], unique=False)
    op.add_column('listings', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('listings', sa.Column('featured_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('listings', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_listings_expires_at'), 'listings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_listings_featured_until'), 'listings', ['featured_until'], unique=False)
    # ### end Alembic commands ###

    # Give existing listings a full window measured from the migration, not
    # from their creation date. Backfilling created_at + 30 days would expire
    # most of the existing catalogue the moment the sweep first runs, which is
    # a data-loss-shaped surprise rather than a feature rollout.
    op.execute(
        "UPDATE listings SET expires_at = now() + interval '30 days' "
        "WHERE status = 'active' AND deleted_at IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_featured_until'), table_name='listings')
    op.drop_index(op.f('ix_listings_expires_at'), table_name='listings')
    op.drop_column('listings', 'expires_at')
    op.drop_column('listings', 'featured_until')
    op.drop_column('listings', 'view_count')
    op.drop_index('ix_listing_views_listing_id_created_at', table_name='listing_views')
    op.drop_table('listing_views')
    # ### end Alembic commands ###
