"""add navigation menus and site settings

Seeds the navigation exactly as it was in JSX the day this landed, so the
navbar and footer are unchanged on the deploy that introduces them.

Revision ID: b353331cb102
Revises: f70ce888ab57
Create Date: 2026-08-06 18:52:41.869627

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b353331cb102'
down_revision: Union[str, None] = 'f70ce888ab57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nav_menus',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('location', sa.Enum('navbar', 'footer', name='nav_location'), nullable=False),
    sa.Column('translation_key', sa.String(length=64), nullable=True),
    sa.Column('label', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nav_menus')),
    sa.UniqueConstraint('key', name=op.f('uq_nav_menus_key'))
    )
    op.create_index('ix_nav_menus_location_sort', 'nav_menus', ['location', 'sort_order'], unique=False)
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_site_settings_key'))
    )
    op.create_table('nav_links',
    sa.Column('menu_id', sa.Uuid(), nullable=False),
    sa.Column('translation_key', sa.String(length=64), nullable=True),
    sa.Column('label', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('visibility', sa.Enum('always', 'signed_in', 'signed_out', name='nav_visibility'), server_default='always', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['nav_menus.id'], name=op.f('fk_nav_links_menu_id_nav_menus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nav_links'))
    )
    op.create_index(op.f('ix_nav_links_menu_id'), 'nav_links', ['menu_id'], unique=False)
    op.create_index('ix_nav_links_menu_sort', 'nav_links', ['menu_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###

    _seed()




# --- seed --------------------------------------------------------------------
#
# The navigation exactly as it was in JSX the day this landed: same menus,
# same links, same order, same sign-in rules. Labels are carried as
# `translation_key` rather than as text, so nothing here duplicates the
# message catalogues and both languages stay correct for every link an admin
# has not touched.

NAVBAR = [
    # (translation_key, href, icon, visibility)
    ("nav.browse", "/listings", "Store", "always"),
    ("nav.browseShops", "/shops", "ShoppingBag", "always"),
    ("nav.sell", "/listings/new", "PlusCircle", "signed_in"),
    ("nav.inbox", "/inbox", "MessageSquare", "signed_in"),
    ("nav.myShops", "/shops/dashboard", "ShoppingBag", "signed_in"),
]

FOOTER = [
    (
        "footer-marketplace",
        "footer.marketplace",
        [
            ("footer.browseListings", "/listings"),
            ("shops.browseTitle", "/shops"),
            ("footer.sellAnItem", "/listings/new"),
            ("footer.openShop", "/shops/dashboard"),
            ("footer.myDashboard", "/dashboard"),
        ],
    ),
    (
        "footer-account",
        "footer.account",
        [
            ("footer.logIn", "/login"),
            ("footer.signUp", "/signup"),
            ("nav.inbox", "/inbox"),
            ("footer.resetPassword", "/forgot-password"),
        ],
    ),
    (
        "footer-campus",
        "footer.campus",
        [
            ("footer.university", "https://juniv.edu"),
            # Safety guidance and the community rules both live in the Terms.
            ("footer.safetyTips", "/terms#meeting-safely"),
            ("footer.communityRules", "/terms"),
            ("footer.terms", "/terms"),
            ("footer.privacy", "/privacy"),
        ],
    ),
]


def _seed() -> None:
    menus = sa.table(
        "nav_menus",
        sa.column("id", sa.Uuid),
        sa.column("key", sa.String),
        # The real columns are enums, not text; declaring them as String here
        # makes the insert fail with DatatypeMismatchError. create_type=False
        # because create_table above already made the types.
        sa.column("location", postgresql.ENUM(name="nav_location", create_type=False)),
        sa.column("translation_key", sa.String),
        sa.column("label", postgresql.JSONB),
        sa.column("sort_order", sa.Integer),
        sa.column("is_active", sa.Boolean),
    )
    links = sa.table(
        "nav_links",
        sa.column("id", sa.Uuid),
        sa.column("menu_id", sa.Uuid),
        sa.column("translation_key", sa.String),
        sa.column("label", postgresql.JSONB),
        sa.column("href", sa.Text),
        sa.column("icon", sa.String),
        sa.column("sort_order", sa.Integer),
        sa.column("is_active", sa.Boolean),
        sa.column("visibility", postgresql.ENUM(name="nav_visibility", create_type=False)),
    )
    settings = sa.table(
        "site_settings",
        sa.column("id", sa.Uuid),
        sa.column("key", sa.String),
        sa.column("value", postgresql.JSONB),
    )

    menu_rows = []
    link_rows = []

    navbar_id = uuid.uuid4()
    menu_rows.append(
        {
            "id": navbar_id,
            "key": "navbar",
            "location": "navbar",
            # No heading: the navbar's menu is never titled on screen.
            "translation_key": None,
            "label": {},
            "sort_order": 0,
            "is_active": True,
        }
    )
    for index, (key, href, icon, visibility) in enumerate(NAVBAR):
        link_rows.append(
            {
                "id": uuid.uuid4(),
                "menu_id": navbar_id,
                "translation_key": key,
                "label": {},
                "href": href,
                "icon": icon,
                "sort_order": index,
                "is_active": True,
                "visibility": visibility,
            }
        )

    for order, (menu_key, heading, items) in enumerate(FOOTER):
        menu_id = uuid.uuid4()
        menu_rows.append(
            {
                "id": menu_id,
                "key": menu_key,
                "location": "footer",
                "translation_key": heading,
                "label": {},
                "sort_order": order,
                "is_active": True,
            }
        )
        for index, (key, href) in enumerate(items):
            link_rows.append(
                {
                    "id": uuid.uuid4(),
                    "menu_id": menu_id,
                    "translation_key": key,
                    "label": {},
                    "href": href,
                    "icon": None,
                    "sort_order": index,
                    "is_active": True,
                    "visibility": "always",
                }
            )

    op.bulk_insert(menus, menu_rows)
    op.bulk_insert(links, link_rows)
    op.bulk_insert(
        settings,
        [
            {
                "id": uuid.uuid4(),
                "key": "navbar_controls",
                "value": {"search": True, "language": True, "theme": True, "notifications": True},
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nav_links_menu_sort', table_name='nav_links')
    op.drop_index(op.f('ix_nav_links_menu_id'), table_name='nav_links')
    op.drop_table('nav_links')
    op.drop_table('site_settings')
    op.drop_index('ix_nav_menus_location_sort', table_name='nav_menus')
    op.drop_table('nav_menus')
    # ### end Alembic commands ###
    # Enums outlive their tables in Postgres; without this a downgrade
    # followed by an upgrade fails with "type already exists".
    sa.Enum(name='nav_visibility').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='nav_location').drop(op.get_bind(), checkfirst=True)
