"""add rate_limit_hits

Revision ID: bc75b0879d9c
Revises: 2d9d01a15fef
Create Date: 2026-08-05 16:17:41.224698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc75b0879d9c'
down_revision: Union[str, None] = '2d9d01a15fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_hits',
    sa.Column('bucket_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limit_hits'))
    )
    op.create_index('ix_rate_limit_hits_bucket_created', 'rate_limit_hits', ['bucket_key', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_limit_hits_bucket_created', table_name='rate_limit_hits')
    op.drop_table('rate_limit_hits')
    # ### end Alembic commands ###
