"""add saved_listings

Revision ID: c4111ed45d6b
Revises: b9efc178bd30
Create Date: 2026-08-05 05:07:06.356481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4111ed45d6b'
down_revision: Union[str, None] = 'b9efc178bd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_listings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_saved_listings_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_listings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_listings')),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_saved_listings_user_listing')
    )
    op.create_index(op.f('ix_saved_listings_listing_id'), 'saved_listings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_saved_listings_user_id'), 'saved_listings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_listings_user_id'), table_name='saved_listings')
    op.drop_index(op.f('ix_saved_listings_listing_id'), table_name='saved_listings')
    op.drop_table('saved_listings')
    # ### end Alembic commands ###
