"""add message image_url

Revision ID: d09a0a8ea5bc
Revises: c4111ed45d6b
Create Date: 2026-08-05 05:26:51.279096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09a0a8ea5bc'
down_revision: Union[str, None] = 'c4111ed45d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'image_url')
    # ### end Alembic commands ###
