"""add category is_active

Existing categories default to active, so nothing disappears from browsing
when this lands. The server default stays on the column rather than being
dropped after backfill: rows are also created by the seed and by fixtures
that do not name every column.

Revision ID: f70ce888ab57
Revises: 3f18e879d84e
Create Date: 2026-08-06 17:53:57.489487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70ce888ab57'
down_revision: Union[str, None] = '3f18e879d84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###
